In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('cars.csv')

In [3]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [7]:
pd.get_dummies(df, columns=['fuel','owner'], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1], test_size=0.2)

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
x_train

        brand  km_driven    fuel         owner
4373    Skoda     150000  Diesel   Third Owner
3689   Maruti      44000  Diesel   First Owner
3397   Toyota     100000  Diesel  Second Owner
6598      BMW      70000  Diesel   Third Owner
2795     Jeep      30000  Diesel   First Owner
...       ...        ...     ...           ...
7311  Hyundai      76000  Diesel   Third Owner
6978   Maruti     120000  Diesel  Second Owner
6599    Skoda      65000  Diesel  Second Owner
3118     Tata      60000  Diesel   First Owner
1828    Volvo      20000  Diesel   First Owner

[6502 rows x 4 columns]

In [19]:
ohe=OneHotEncoder()
ohe.fit(x_train[['fuel','owner']])
x_train_ohe = ohe.transform(x_train[['fuel','owner']]).toarray()
x_test_ohe = ohe.transform(x_test[['fuel','owner']]).toarray()

In [18]:
ohe.transform(x_train[['fuel','owner']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 13004 stored elements and shape (6502, 9)>